extends: airbnb-base
plugins:
    - spellcheck
rules:
    spellcheck/spell-checker:
    - 1
    - comments: true
      strings: true
      identifiers: true
      lang: en_US
      skipWords:
      - healthz
      - dayjs
      - Pragma
      - liveness
      - revalidate
      - paypal
      - mongodb
      - localhost
      - Postback
      - winston
      - printf
      - charset
      - urlencoded
      skipIfMatch:
      - http://[^s]*
      - "^[-\\w]+/[-\\w\\.]+$"
      minLength: 5